<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/login.css" rel="stylesheet" />
    <title>Entrar</title>
</head>

<body class= "login">
    <div class="form-container">
        <p class="title">Entrar</p>
        <form class="form" action="/autenticar" method="post">
            <div class="input-group">
                <label for="username">Email</label>
                <input type="text" name="email" id="username" placeholder="">
            </div>
            <div class="input-group">
                <label for="password">Senha</label>
                <input type="password" name="senha" id="password" placeholder="">
                <div class="forgot">
                    <a rel="noopener noreferrer" href="#">Esqueceu a senha ?</a>
                </div>
            </div>
            <button class="sign"> Entrar</button>
            <?php if($this->view->login == 'erro') { ?>
            <div class="row">
                <div class="alerta">
                <span class="text text-danger"> E-mail e/ou senha inválido(s)</span>
                </div>
            </div>
            <?php } ?>
        </form>
        
        <p class="signup">Não tem uma conta?
            <a rel="noopener noreferrer" href="cadastrarse" class="">Cadastre-se</a>
        </p>
    </div>
</body>

</html>