<?php $usuario = $this->view->usuario; ?>
<div id="cabecalho">
	<div class="logo-search">
		<div class="logo">
			<a href="/telaInicial">
				<img src="/img/logo1.png" alt="">
			</a>
		</div>
	</div>
	<div>
		<ul class="list">
			<li><img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt="" onclick="toggleMenu()"></li>
		</ul>
	</div>
	<div class="sub-menu-wrap" id="subMenu">
		<div class="sub-menu">
			<div class="user-info">
				<img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" class="imagem-perfil-baixo" alt="">
				<h2>
					<?php echo $usuario[0]['nome']; ?>
				</h2>
			</div>
			<hr>

			<a href="/perfil" class="sub-menu-link">
				<img src="img/profile.png" alt="">
				<p>Perfil</p>
				<span>></span>
			</a>

			<a href="/mensagens" class="sub-menu-link">
				<img src="img/mensagens.png" alt="" >
				<p>Mensagens</p>
				<span>></span>
			</a>

			<a href="/sair" class="sub-menu-link">
				<img src="img/logout.png" alt="">
				<p>Sair</p>
				<span>></span>
			</a>

		</div>
	</div>
</div>

<div class="wrapper">
  <section class="chat-area">
    <header>
      <a href="mensagens" class="back-icon"><i class="fas fa-arrow-left"></i></a>
      <img src="<?php echo "/" . $usuario[0]['pathUsuario']; ?>" alt="">
      <div class="details">
        <span>
          <?php echo $usuario[0]['nome']; ?>
        </span>
      </div>
    </header>
    <div class="chat-box">

    </div>
    <form class="typing-area" autocomplete="off">
      <input type="text" class="outgoing_id" name="outgoing_id" value="<?php echo $_SESSION['id_unico']; ?>" hidden>
      <input type="text" class="incoming_id" name="incoming_id" value="<?php echo $usuario[0]['id_unico']; ?>" hidden>
      <input type="text" name="message" class="input-field" placeholder="Digite uma Mensagem" autocomplete="off">
      <button><i class="fab fa-telegram-plane"></i></button>
    </form>
  </section>
</div>

<script src="javascript/chat.js"></script>