<?php $usuario = $this->view->usuario; ?>
<div id="cabecalho">
	<div class="logo-search">
		<div class="logo">
			<a href="/telaInicial">
				<img src="/img/logo1.png" alt="">
			</a>
		</div>
	</div>
	<div>
		<ul class="list">
			<li><img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt="" onclick="toggleMenu()"></li>
		</ul>
	</div>
	<div class="sub-menu-wrap" id="subMenu">
		<div class="sub-menu">
			<div class="user-info">
				<img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" class="imagem-perfil-baixo" alt="">
				<h2>
					<?php echo $usuario[0]['nome']; ?>
				</h2>
			</div>
			<hr>

			<a href="/perfil" class="sub-menu-link">
				<img src="img/profile.png" alt="">
				<p>Perfil</p>
				<span>></span>
			</a>

			<a href="/mensagens" class="sub-menu-link">
				<img src="img/mensagens.png" alt="" >
				<p>Mensagens</p>
				<span>></span>
			</a>

			<a href="/sair" class="sub-menu-link">
				<img src="img/logout.png" alt="">
				<p>Sair</p>
				<span>></span>
			</a>

		</div>
	</div>
</div>

<div class="container-form">
    <div class="form-wrapper">
        <div class="modal__header">
            <span class="modal__title">Criar uma Publicacão</span><a href="/telaInicial" class="button button--icon">
                <svg width="24" viewBox="0 0 24 24" height="24" xmlns="http://www.w3.org/2000/svg">
                    <path fill="none" d="M0 0h24v24H0V0z"></path>
                    <path
                        d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z">
                    </path>
                </svg>
            </a>
        </div>
        <div class="modal__body">
            <form class="custom-form" enctype="multipart/form-data" method="post" action="/publicar">
                <div class="input">
                    <label class="input__label" for="titulo">Título:</label>
                    <input class="input__field" type="text" name="titulo" id="titulo">
                    <p class="input__description">Descrição do titulo</p>
                </div>
                <div class="input">
                    <label class="input__label" for="texto">Texto:</label>
                    <textarea class="input__field input__field--textarea" name="texto" id="texto"></textarea>
                    <p class="input__description">Descrição do texto</p>
                </div>
                <div class="input">
                    <label for="arquivo">Selecione o arquivo:</label>
                    <input class="form-control" type="file" name="arquivo" id="arquivo">
                </div>
        </div>
        <div class="l2">
            <button type="submit">Publicar</button>
        </div>
    </div>
</div>