<div class="container-form">
    <div class="form-wrapper">
        <form class="custom-form" enctype="multipart/form-data" method="post" action="/publicar">
            <div class="form-group">
                <label for="titulo">Título:</label>
                <input class="form-control" type="text" name="titulo" id="titulo">
            </div>
            <div class="form-group">
                <label for="texto">Texto:</label>
                <textarea class="form-control" name="texto" id="texto" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="arquivo">Selecione o arquivo:</label>
                <input class="form-control" type="file" name="arquivo" id="arquivo">
            </div>
            <div class="l2">
                <button type="submit" >Publicar</button>
			</div>

        </form>
    </div>
</div>
