<?php $usuario = $this->view->usuario;
$usuarioPesquisado = $this->view->usuarioPesquisado;
$ultimasMensagens = $this->view->ultimasMensagens ?>
<div id="cabecalho">
	<div class="logo-search">
		<div class="logo">
			<a href="/telaInicial">
				<img src="/img/logo1.png" alt="">
			</a>
		</div>
	</div>
	<div>
		<ul class="list">
			<li><img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt="" onclick="toggleMenu()"></li>
		</ul>
	</div>
	<div class="sub-menu-wrap" id="subMenu">
		<div class="sub-menu">
			<div class="user-info">
				<img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" class="imagem-perfil-baixo" alt="">
				<h2>
					<?php echo $usuario[0]['nome']; ?>
				</h2>
			</div>
			<hr>

			<a href="/perfil?id=<?php echo $usuario[0]['id']; ?>" class="sub-menu-link">
				<img src="img/profile.png" alt="">
				<p>Perfil</p>
				<span>></span>
			</a>

			<a href="/mensagens" class="sub-menu-link">
				<img src="img/mensagens.png" alt="">
				<p>Mensagens</p>
				<span>></span>
			</a>

			<a href="/sair" class="sub-menu-link">
				<img src="img/logout.png" alt="">
				<p>Sair</p>
				<span>></span>
			</a>

		</div>
	</div>
</div>

<div class="wrapper">
	<section class="users">
		<header>
			<div class="content">
				<img src="<?php echo "/" . $usuario[0]['pathUsuario']; ?>" alt="">
				<div class="details">
					<span>
						<?php echo $usuario[0]['nome']; ?>
					</span>
				</div>
			</div>
		</header>
		<form action="" id="searchForm">
			<div class="search">
				<span class="text">Pesquise por um usuário</span>
				<input type="text" name="usuario" id="search-bar" class="search-bar"
					placeholder="Digite o nome do Usuário">
				<button type="submit"><i class="fas fa-search"></i></button>
			</div>
		</form>
		<?php if ($usuarioPesquisado != null && $usuarioPesquisado[0]['id'] != $_SESSION['id']) { ?>
			<div class="users-list">
				<a href="/chat?user_id=<?php echo $usuarioPesquisado[0]['id_unico']; ?>">
					<div class="content">
						<img src="<?php echo "/" . $usuarioPesquisado[0]['pathUsuario']; ?>" alt="">
						<div class="details">
							<span>
								<?php echo $usuarioPesquisado[0]['nome']; ?>
							</span>
						</div>
					</div>
				</a>
			</div>
		<?php } else{ ?>
		<div class="users-list">
			<?php foreach ($ultimasMensagens as $mensagem){ ?>
				<a href="/chat?user_id=<?php echo $mensagem['id_unico']; ?>">
					<div class="content">
						<img src="<?php echo "/" . $mensagem['pathUsuario']; ?>" alt="">
						<div class="details">
							<span>
								<?php echo $mensagem['nome']; ?>
							</span>
							<p>
								<?php echo $mensagem['msg']; ?>
							</p>
						</div>
					</div>
				</a>
			<?php } }?>

		</div>


	</section>
</div>

<script src="/javascript/users.js"></script>