<?php $usuario = $this->view->usuario; ?>
<div id="cabecalho">
    <div class="logo-search">
        <div class="logo">
            <a href="/telaInicial">
                <img src="/img/logo1.png" alt="">
            </a>
        </div>
    </div>
    <div>
        <ul class="list">
            <li><img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt="" onclick="toggleMenu()"></li>
        </ul>
    </div>
    <div class="sub-menu-wrap" id="subMenu">
        <div class="sub-menu">
            <div class="user-info">
                <img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" class="imagem-perfil-baixo" alt="">
                <h2>
                    <?php echo $usuario[0]['nome']; ?>
                </h2>
            </div>
            <hr>

            <a href="/perfil?id=<?php echo $usuario[0]['id']; ?>" class="sub-menu-link">
                <img src="img/profile.png" alt="">
                <p>Perfil</p>
                <span>></span>
            </a>

            <a href="/mensagens" class="sub-menu-link">
                <img src="img/mensagens.png" alt="">
                <p>Mensagens</p>
                <span>></span>
            </a>

            <a href="/sair" class="sub-menu-link">
                <img src="img/logout.png" alt="">
                <p>Sair</p>
                <span>></span>
            </a>

        </div>
    </div>
</div>
<div id="fundoDesfocado">
    <div id="janelaEdicaoPerfil" style="display:none;">
        <div class="form-perfil">
            <a id="fecharJanela" class="back-icon"><i class="fas fa-arrow-left"></i></a>
            <form class="custom-form" enctype="multipart/form-data" method="post" action="/atualizarPerfil">
                <div class="form-group personal-image">
                    <label for="avatar" class="label-avatar">
                        <input type="file" name="avatar" id="avatar" onchange="previewImage(event)" />
                        <figure class="personal-figure">
                            <img id="avatar-preview" class="personal-avatar" alt="avatar"
                                src="<?php echo "/" . $usuario[0]['pathUsuario']; ?>">
                        </figure>
                    </label>
                </div>

                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <div class="form-editar-perfil">
                        <input type="text" class="form-control" name="nome" id="nome"
                            value="<?php echo $usuario[0]['nome']; ?>">

                    </div>
                </div>

                <div class="form-group">
                    <label for="email">Email:</label>
                    <div class="form-editar-perfil">

                        <input type="email" class="form-control" name="email" id="email"
                            value="<?php echo $usuario[0]['email']; ?>">

                    </div>
                </div>

                <div class="form-group">
                    <label for="senha">Senha:</label>
                    <div class="form-editar-perfil">
                        <input type="password" class="form-control" name="senha" id="senha">

                    </div>
                </div>

                <div class="form-group">
                    <label for="estado">Selecione a Cidade:</label>
                    <div class="form-editar-perfil">
                        <select class="form-select" name="estado" id="estado">
                            <option value="<?php echo $usuario[0]['id_estado']; ?>" selected>
                                <?php echo $usuario[0]['nome_cidade']; ?>
                            </option>
                            <?php foreach ($this->view->estados as $estado) { ?>
                                <option value="<?php echo $estado->id ?>">
                                    <?php echo $estado->nome_cidade; ?>
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <?php if (isset($_GET['email']) && $_GET['email'] == 'cadastrado') { ?>
                    <small class="form-text text-danger"> E-mail já cadastrado!</small>
                <?php } ?>
                <div class="l2">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </div>
            </form>


        </div>
    </div>
</div>

<div id="principal">
    <div class="perfil">
        <div class="card">
            <div class="img">
                <img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt="">
            </div>
            <span>
                <?php
                echo $usuario[0]['nome'];
                ?>
            </span>
            <a class="add" href="/sair">
                <!-- Sair -->
            </a>
            <?php if ($_GET['id'] == $_SESSION['id']) { ?>
                <button id="editarPerfilButton">Editar Perfil</button>
            <?php } ?>
        </div>
    </div>

    <div class="conteudo">
        <p class="minhas-publicações">Publicações</p>
        <div class="publicacoes">
            <?php if ($this->view->total_publicacoes['total'] == 0) { ?>
                <div class="alert alert-danger" role="alert">
                    Nenhum resultado encontrado
                </div>

            <?php }
            ;

            foreach ($this->view->publicacoes as $id_publicacao => $publicacao) { ?>
                <div class="publicacao" onclick="window.location.href='/publicacao?id=<?php echo $publicacao['id'] ?>'">
                    <!-- <div class="linha-1">
                        <div class="publicar-perfil">
                            <a href=""> <img src="<?php echo "/" . $publicacao['pathUsuario']; ?>" alt=""></a>
                        </div>
                        <div class="nome">
                            <?php echo $publicacao['nome'] ?>
                            <div class="lugar">
                                <?php echo $publicacao['nome_cidade'] . ' · ' . $publicacao['data'] ?>
                            </div>
                        </div>
                    </div> -->
                    <img class="imagem-publicacao" src="<?php
                    if ($publicacao['path'] != "") {
                        echo "/" . $publicacao['path'];
                    } else {
                        echo "/arquivos" . '/semFotoPublicacao.jpg';
                    }

                    ?>" alt="" class="img-fluid">
                    <div class="linha-2">
                        <p><strong>
                                <?php echo $publicacao['titulo'] ?>
                            </strong></p>
                    </div>
                    <?php if ($_GET['id'] == $_SESSION['id']) { ?>
                        <form class="form-delete" method="post" action="/excluirPublicacao?id=<?php echo $publicacao['id'] ?>">
                            <button class="delete-button">
                                <svg class="delete-svgIcon" viewBox="0 0 448 512">
                                    <path
                                        d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z">
                                    </path>
                                </svg>
                            </button>
                        </form>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>

        <div class="paginacao">
            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="?busca=<?php echo $this->view->busca ?>&pagina=1"
                            tabindex="-1">Primeira</a>
                    </li>
                    <?php for ($i = 1; $i <= $this->view->total_de_paginas; $i++) { ?>

                        <li class="page-item <?php echo $this->view->pagina_ativa == $i ? 'active' : '' ?>">
                            <a class="page-link " href="?busca=<?php echo $this->view->busca ?>&pagina=<?php echo $i ?>">
                                <?php echo $i ?>
                            </a>
                        </li>

                        <li class="page-item">
                        <?php } ?>
                        <a class="page-link"
                            href="?busca=<?php echo $this->view->busca ?>&pagina=<?php echo $this->view->total_de_paginas ?>">Ultima</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<footer class="rodape">
    <img src="/img/logo1.png" alt="Logo Compartilhando Esperança" class="logo">
    <p>&copy; 2023 <span id="anoAtual"></span> Compartilhando Esperança. Todos os direitos reservados.</p>
</footer>

<script>
    function previewImage(event) {
        const input = event.target;
        const preview = document.getElementById('avatar-preview');
        const file = input.files[0];
        const reader = new FileReader();

        reader.onload = function () {
            preview.src = reader.result;
        }

        if (file) {
            reader.readAsDataURL(file);
        }
    }
    // function enableField(fieldId) {
    //     var field = document.getElementById(fieldId);
    //     field.disabled = !field.disabled;
    //     var submitButton = document.querySelector('#janelaEdicaoPerfil button[type="submit"]');
    //     submitButton.disabled = !submitButton.disabled;
    // }

    document.getElementById('editarPerfilButton').addEventListener('click', function () {
        document.getElementById('fundoDesfocado').style.display = 'flex';
    });

    document.getElementById('fecharJanela').addEventListener('click', function () {
        document.getElementById('fundoDesfocado').style.display = 'none';
    });

    document.getElementById('editarPerfilButton').addEventListener('click', function () {
        document.getElementById('janelaEdicaoPerfil').style.display = 'block';
    });
</script>