<?php $usuario = $this->view->usuario; ?>
<div class="container">
    <a class="menuItem" href="/sair">
        Sair
    </a>
    <div class="row d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="col-lg-8 col-md-10 col-sm-12 tweetBox" style="max-width: 600px;">
            <form class="tweet-form" enctype="multipart/form-data" method="post" action="/atualizarPerfil">
                <div class="personal-image">
                    <label class="label">
                        <input type="file" name="avatar" />
                        <figure class="personal-figure">
                            <img src="<?php echo "/" . $usuario[0]['pathUsuario']; ?>" class="personal-avatar"
                                alt="avatar">

                            <figcaption class="personal-figcaption">
                                <img
                                    src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                            </figcaption>
                        </figure>
                    </label>
                </div>
                <div class="mb-3">
                    <label class="form-label">Nome:</label>
                    <input type="text" class="form-control" name="nome" value="<?php echo $usuario[0]['nome']; ?>"
                        required>
                </div>

                <div class="mb-3">
                    <label class="form-label">Email:</label>
                    <input type="email" class="form-control" name="email" value="<?php echo $usuario[0]['email']; ?>"
                        disabled>
                </div>

                <div class="mb-3">
                    <label class="form-label">Senha:</label>
                    <input type="password" class="form-control" name="senha" value="<?php echo $usuario[0]['senha']; ?>"
                        disabled>
                </div>

                <div class="mb-3">
                    <label class="form-label">Selecione o Estado:</label>
                    <select class="form-select" name="estado" id="estado">
                        <?php foreach ($this->view->estados as $estado) { ?>
                            <option value="<?php echo $estado->id ?>"><?php echo $estado->nome_estado; ?></option>
                        <?php } ?>
                    </select>
                </div>



                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>