<?php $usuario = $this->view->usuario; ?>
<div id="cabecalho">
	<div class="logo-search">
		<div class="logo">
			<a href="/telaInicial">
				<img src="/img/logo1.png" alt="">
			</a>
		</div>
	</div>
	<div>
		<ul class="list">
			<li class="msg"><a href="/mensagens" class="a">Mensagens</a></li>
			<!-- <li class="feed"><a href="/telaInicial" class="a">Feed</a></li>
			<li class="notificacoes"><a href="notificacoes.php" class="a">Perfil</a></li> -->
			<li><a href="/perfil" class="a"><img src="/img/perfil.svg" alt=""></a></li>
			<!-- <li ><a href="\perfil" class="a"><img src="<?php echo "/" . $_SESSION['path']; ?>" alt=""></a></li> -->

		</ul>
	</div>
</div>




<div id="principal">
	<div class="perfil">
		<div class="card">
			<div class="img"> <img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt=""></div>
			<span>Olá,
				<?php
				echo $usuario[0]['nome'];
				?>
			</span>
			<a class="add" href="/sair">
                Sair
            </a>
			<form action="/perfil">
				<button>Perfil</button>
			</form>
		</div>
	</div>

	<div class="conteudo">
		<div class="publicar">
			<div class="fazerPublicacao">
				<form action="/fazerPublicacao">
					<div class="l2">
						<button>Fazer Uma Publicação</button>
					</div>
				</form>
			</div>

		</div>

		<hr>

		<form action="" class="search-container">
			<div class="col mt-2 d-flex justify-content-end">
				<input name="busca" type="text" id="search-bar" placeholder="Busca">
				<a href="#"><img class="search-icon"
						src="http://www.endlessicons.com/wp-content/uploads/2012/12/search-icon.png"></a>
			</div>

		</form>
		<div class="publicacoes">
			<?php if ($this->view->total_publicacoes['total'] == 0) { ?>
				<div class="alert alert-danger" role="alert">
					Nenhum resultado encontrado
				</div>

			<?php }
			;

			foreach ($this->view->publicacoes as $id_publicacao => $publicacao) { ?>
				 <div class="publicacao" onclick="window.location.href='/publicacao?id=<?php echo $publicacao['id']?>'">
					<div class="linha-1">
						<div class="publicar-perfil">
							<a href=""> <img src="<?php echo "/" . $publicacao['pathUsuario']; ?>" alt=""></a>
						</div>
						<div class="nome">
							<?php echo $publicacao['nome'] ?>
							<div class="lugar">
								<?php echo $publicacao['nome_cidade'] . ' · ' . $publicacao['data'] ?>
							</div>
						</div>
					</div>
					<div class="linha-2">
						<p><strong>
								<?php echo $publicacao['titulo'] ?>
							</strong></p>
					</div>
						<img class="imagem-publicacao" src="<?php
							if($publicacao['path'] != ""){
							 echo "/" . $publicacao['path']; 
							} else{
								echo "/arquivos" . '/semFotoPublicacao.jpg'; 
							}
							 
							 ?>" alt="" class="img-fluid">
					<form>
						<!-- <div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								</div> -->
					</form>
				</div>
			<?php } ?>
		</div>

		<div class="paginacao">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item">
							<a class="page-link" href="?busca=<?php echo $this->view->busca ?>&pagina=1"
								tabindex="-1">Primeira</a>
						</li>
						<?php for ($i = 1; $i <= $this->view->total_de_paginas; $i++) { ?>

							<li class="page-item <?php echo $this->view->pagina_ativa == $i ? 'active' : '' ?>">
								<a class="page-link "
									href="?busca=<?php echo $this->view->busca ?>&pagina=<?php echo $i ?>">
									<?php echo $i ?>
								</a>
							</li>

							<li class="page-item">
							<?php } ?>
							<a class="page-link"
								href="?busca=<?php echo $this->view->busca ?>&pagina=<?php echo $this->view->total_de_paginas ?>">Ultima</a>
						</li>
					</ul>
				</nav>
			</div>


	</div>

	<div class="direita">
		<!-- <div class="quemSeguir">
			<span class="quemSeguirTitulo">Quem seguir</span><br />
			<hr />
			<a href="#" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
		</div> -->
	</div>
</div>