<?php if (isset($this->view->usuario)) {
	$usuario = $this->view->usuario;
} ?>
<div id="cabecalho">
	<div class="logo-search">
		<div class="logo">
			<a href="/telaInicial">
				<img src="/img/logo1.png" alt="">
			</a>
		</div>
	</div>
	<div>
		<ul class="list">
			<li><img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt="" onclick="toggleMenu()"></li>
		</ul>
	</div>
	<div class="sub-menu-wrap" id="subMenu">
		<div class="sub-menu">
			<div class="user-info">
				<img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" class="imagem-perfil-baixo" alt="">
				<h2>
					<?php echo $usuario[0]['nome']; ?>
				</h2>
			</div>
			<hr>

			<a href="/perfil?id=<?php echo $usuario[0]['id']; ?>" class="sub-menu-link">
				<img src="img/profile.png" alt="">
				<p>Perfil</p>
				<span>></span>
			</a>

			<a href="/mensagens" class="sub-menu-link">
				<img src="img/mensagens.png" alt="">
				<p>Mensagens</p>
				<span>></span>
			</a>

			<a href="/sair" class="sub-menu-link">
				<img src="img/logout.png" alt="">
				<p>Sair</p>
				<span>></span>
			</a>

		</div>
	</div>
</div>

<div id="principal">
	<!-- <div class="perfil">
		<div class="card">
			 <div class="img"> <img src="<?php echo '/' . $usuario[0]['pathUsuario']; ?>" alt=""></div>
			<span>Olá,
				<?php
				echo $usuario[0]['nome'];
				?>
			</span>
			<a class="add" href="/sair">
				Sair
			</a>
			<form action="/perfil">
				<button>Perfil</button>
			</form> 
		</div>
	</div> -->

	<div class="conteudo">
		<div class="publicar">
			<div class="fazerPublicacao">
				<form action="/fazerPublicacao">
					<div class="l2">
						<button>Fazer Uma Publicação</button>
					</div>
				</form>
			</div>

		</div>

		<hr>

		<form action="" class="search-container">
			<div class="col mt-2 d-flex justify-content-end">
				<input name="busca" type="text" id="search-bar" placeholder="Busca">
				<img class="search-icon" src="http://www.endlessicons.com/wp-content/uploads/2012/12/search-icon.png">
			</div>

		</form>
		<div class="publicacoes">
			<?php if ($this->view->total_publicacoes['total'] == 0) { ?>
				<div class="alert alert-danger" role="alert">
					Nenhum resultado encontrado
				</div>

			<?php }
			;

			foreach ($this->view->publicacoes as $id_publicacao => $publicacao) { ?>
				<div class="publicacao" onclick="window.location.href='/publicacao?id=<?php echo $publicacao['id'] ?>'">
					<!-- <div class="linha-1">
						<div class="publicar-perfil">
							<a href=""> <img src="<?php echo "/" . $publicacao['pathUsuario']; ?>" alt=""></a>
						</div>
						<div class="nome">
							<?php echo $publicacao['nome'] ?>
							<div class="lugar">
								<?php echo $publicacao['nome_cidade'] . ' · ' . $publicacao['data'] ?>
							</div>
						</div>
					</div> -->

					<img class="imagem-publicacao" src="<?php
					if ($publicacao['path'] != "") {
						echo "/" . $publicacao['path'];
					} else {
						echo "/arquivos" . '/semFotoPublicacao.jpg';
					}
					?>" alt="" class="img-fluid">
					<div class="linha-2">
						<p>
							<?php echo $publicacao['titulo'] ?>
						</p>
					</div>
					<form>
						<!-- <div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								</div> -->
					</form>
				</div>
			<?php } ?>
		</div>
			<div class="paginacao">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item">
							<a class="page-link" href="?busca=<?php echo $this->view->busca ?>&pagina=1"
								tabindex="-1">Primeira</a>
						</li>
						<?php for ($i = 1; $i <= $this->view->total_de_paginas; $i++) { ?>

							<li class="page-item <?php echo $this->view->pagina_ativa == $i ? 'active' : '' ?>">
								<a class="page-link " href="?busca=<?php echo $this->view->busca ?>&pagina=<?php echo $i ?>">
									<?php echo $i ?>
								</a>
							</li>

							<li class="page-item">
							<?php } ?>
							<a class="page-link"
								href="?busca=<?php echo $this->view->busca ?>&pagina=<?php echo $this->view->total_de_paginas ?>">Ultima</a>
						</li>
					</ul>
				</nav>
			</div>


	</div>

	<!-- <div class="direita">
 <div class="quemSeguir">
			<span class="quemSeguirTitulo">Quem seguir</span><br />
			<hr />
			<a href="#" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
		</div> 
	</div> -->
</div>
<footer class="rodape">
	<img src="/img/logo1.png" alt="Logo Compartilhando Esperança" class="logo">
	<p>&copy; 2023 Compartilhando Esperança. Todos os direitos reservados.</p>
</footer>


<script>
	let subMenu = document.getElementById("subMenu");

	function toggleMenu() {
		subMenu.classList.toggle("open-menu");
	}
</script>